In [1]:
import pandas as pd

In [5]:
dict = {'d1':{'t1':['a','b','c'],
              't2':['a','b','c']
              },
        'd2':{'t1':['a','b','c'],
              't2':['a','b','c']
              },
        
        
        }
df = pd.DataFrame(dict)
df

           d1         d2
t1  [a, b, c]  [a, b, c]
t2  [a, b, c]  [a, b, c]

In [6]:
rtn = pd.read_csv('raw_data.csv')
rtn

,Exam,Day,Time,Courses
0,MID EXAM,Day 1,9:00 AM - 11:00 AM,ENG 101/ENG 1011 (BSCSE/BSDS)
1,MID EXAM,Day 1,9:00 AM - 11:00 AM,CSE 308/CSE 4609
2,MID EXAM,Day 1,9:00 AM - 11:00 AM,IPE 401/ IPE 3401 (BSCSE/BSDS)
3,MID EXAM,Day 1,11:30 AM - 1:30 PM,ENG 1013/ENG 103 (BSCSE/BSDS)
4,MID EXAM,Day 1,11:30 AM - 1:30 PM,TEC 2499 (BSCSE/BSDS)
...,...,...,...,...
60,MID EXAM,Day 7,2:00 PM - 4:00 PM,PHY 2105/ PHY 105 (BSCSE/BSDS)
61,MID EXAM,Day 7,2:00 PM - 4:00 PM,CSE 4883/CSE 483 (Elective/Opt II)
62,MID EXAM,Day 7,2:00 PM - 4:00 PM,CSE 4486 (New offer)
63,MID EXAM,Day 7,2:00 PM - 4:00 PM,CSE 4496/CSE 496 (Elective/ Opt II) (Only Fina...
64,MID EXAM,Day 7,2:00 PM - 4:00 PM,CSE 4533 (Elective)

AttributeError: 'DataFrameGroupBy' object has no attribute 'groupby'

In [9]:
rtn.head()

,Exam,Day,Time,Courses
0,MID EXAM,Day 1,9:00 AM - 11:00 AM,ENG 101/ENG 1011 (BSCSE/BSDS)
1,MID EXAM,Day 1,9:00 AM - 11:00 AM,CSE 308/CSE 4609
2,MID EXAM,Day 1,9:00 AM - 11:00 AM,IPE 401/ IPE 3401 (BSCSE/BSDS)
3,MID EXAM,Day 1,11:30 AM - 1:30 PM,ENG 1013/ENG 103 (BSCSE/BSDS)
4,MID EXAM,Day 1,11:30 AM - 1:30 PM,TEC 2499 (BSCSE/BSDS)
10,MID EXAM,Day 2,9:00 AM - 11:00 AM,CSI 411/CSE 4611 (Elective)
11,MID EXAM,Day 2,9:00 AM - 11:00 AM,CSI 421/CSI 4621 (Elective)
12,MID EXAM,Day 2,9:00 AM - 11:00 AM,CSI 221/ CSE 3521(BSCSE/BSDS)
13,MID EXAM,Day 2,9:00 AM - 11:00 AM,CSE 1110/ CSE 1110 (Only Final Exam)
14,MID EXAM,Day 2,11:30 AM - 1:30 PM,CSE 425/ CSE 4325
19,MID EXAM,Day 3,2:00 PM - 4:00 PM,CSE 493 (Op II)/ CSE 4983 (Elective)
20,MID EXAM,Day 3,9:00 AM - 11:00 AM,CSI 341/ CSE 3811
21,MID EXAM,Day 3,9:00 AM - 11:00 AM,CSE 445/ CSI 451 (Elective/Opt II)
22,MID EXAM,Day 3,11:30 AM - 1:30 PM,CSI 219/ CSE 2213 (BSCSE/BSDS)
23,MID EXAM,Day 3,11:30 AM - 1:30 PM,CSE 469 (Op II)/ PMG 4101 (BSCSE/BSDS)
28,MID EXAM,Day 4,9:00 AM - 11:00 AM,CSI 233/ CSE 2233
29,MID EXAM,Day 4,9:00 AM - 11:00 AM,CSE 465 (Op II)/ CSE 4165 (Elective)
30,MID EXAM,Day 4,11:30 AM - 1:30 PM,CSI 121/ CSE 1111
31,MID EXAM,Day 4,11:30 AM - 1:30 PM,DS 1501 (BSDS)
32,MID EXAM,Day 4,11:30 AM - 1:30 PM,CSE 4435 (Elective)
36,MID EXAM,Day 5,9:00 AM - 11:00 AM,MATH 201/MATH 2201 (BSCSE) MATH 1153 (BSDS)
37,MID EXAM,Day 5,9:00 AM - 11:00 AM,CSI 311/ CSE 3411
38,MID EXAM,Day 5,9:00 AM - 11:00 AM,EEE 4261 (Only Final Exam)
39,MID EXAM,Day 5,11:30 AM - 1:30 PM,CSI 227/ CSE 2217 (BSCSE/BSDS)
40,MID EXAM,Day 5,11:30 AM - 1:30 PM,DS 1101 (BSDS)
43,MID EXAM,Day 6,9:00 AM - 11:00 AM,DS 3821 (New offer)
44,MID EXAM,Day 6,11:30 AM - 1:30 PM,BDS 1201 (BSCSE)
45,MID EXAM,Day 6,11:30 AM - 1:30 PM,ECO 213/ ECO 4101 (BSCSE/BSDS)
46,MID EXAM,Day 6,11:30 AM - 1:30 PM,MATH 151/ MATH 1151 (BSCSE/BSDS)
47,MID EXAM,Day 6,11:30 AM - 1:30 PM,CSE 4783 (Elective)
53,MID EXAM,Day 7,9:00 AM - 11:00 AM,CSI 2101/ PSY 101 (BSCSE/BSDS)
54,MID EXAM,Day 7,9:00 AM - 11:00 AM,CSE 499/CSE 491 (Elective/Opt II)
55,MID EXAM,Day 7,9:00 AM - 11:00 AM,CSE 1112/ CSI 122 (Only Final Exam)
56,MID EXAM,Day 7,11:30 AM - 1:30 PM,CSI 217/CSI 2215 (BSCSE/BSDS)
57,MID EXAM,Day 7,11:30 AM - 1:30 PM,DS 1502 (BSDS) (Only Final Exam)